let
    Source = Date.AddMonths(#date(Date.Year(DateTime.LocalNow()),#"Calendar Start Month",1),-Value.Multiply(Number.FromText(#"Years of Historical Data"),12)),
    #"List of First Seven Days" = List.Dates(Source, 7 ,#duration(1,0,0,0)),
    #"Converted to Table1" = Table.FromList(#"List of First Seven Days", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed 'Date'" = Table.RenameColumns(#"Converted to Table1",{{"Column1", "Calendar Start Date"}}),
    #"Changed to Date Format" = Table.TransformColumnTypes(#"Renamed 'Date'",{{"Calendar Start Date", type date}}),
    #"Inserted Day Name" = Table.AddColumn(#"Changed to Date Format", "Day Name", each Date.DayOfWeekName([Calendar Start Date]), type text),
    #"Filtered to Sunday" = Table.SelectRows(#"Inserted Day Name", each ([Day Name] = "Sunday")),
    #"Removed Day Name Column" = Table.RemoveColumns(#"Filtered to Sunday",{"Day Name"}),
    #"Added Today Column" = Table.AddColumn(#"Removed Day Name Column", "Today", each Date.From(DateTime.LocalNow()),type date),
    #"Added List of Dates Column" = Table.AddColumn(#"Added Today Column", "Dates", each {Number.From([Calendar Start Date])..Number.From([Today])}),
    #"Expanded Dates" = Table.ExpandListColumn(#"Added List of Dates Column", "Dates"),
    #"Changed to List of Dates" = Table.TransformColumnTypes(#"Expanded Dates",{{"Dates", type date}}),
    #"Added Date ID" = Table.AddIndexColumn(#"Changed to List of Dates", "Date ID", 1, 1),
    #"Inserted Day Name1" = Table.AddColumn(#"Added Date ID", "Day Name", each Date.DayOfWeekName([Dates]), type text),
    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day Name1", "Day of Week", each Date.DayOfWeek([Dates],Day.Sunday)+1, Int64.Type),
    #"Inserted Start of Week" = Table.AddColumn(#"Inserted Day of Week", "Start of Week", each Date.StartOfWeek([Dates],Day.Sunday), type date),
    #"Inserted End of Week" = Table.AddColumn(#"Inserted Start of Week", "End of Week", each Date.EndOfWeek([Dates],Day.Sunday), type date),
    #"Added Week ID" = Table.AddColumn(#"Inserted End of Week", "Week ID", each Number.RoundUp([Date ID]/7),Int64.Type),
    #"Added Start of Week DD/MM" = Table.AddColumn(#"Added Week ID", "Start of Week DD/MM", each Date.ToText([Start of Week],"dd/MM"),type text),
    #"Added End of Week DD/MM" = Table.AddColumn(#"Added Start of Week DD/MM", "End of Week DD/MM", each Date.ToText([End of Week],"dd/MM"),type text),
    #"Inserted Week of Year" = Table.AddColumn(#"Added End of Week DD/MM", "Week of Year", each Date.WeekOfYear([Start of Week]), Int64.Type),
    #"Inserted Week of Year ID" = Table.AddColumn(#"Inserted Week of Year", "Week of Year ID", each if [Week of Year] < #"Inserted Week of Year"{1}[Week of Year] then 52 - ((#"Inserted Week of Year"{1}[Week of Year] - 1) - [Week of Year]) else [Week of Year] - (#"Inserted Week of Year"{1}[Week of Year] - 1), Int64.Type),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Week of Year ID", "Month Name", each Date.MonthName([Dates]), type text),
    #"Inserted Month Number" = Table.AddColumn(#"Inserted Month Name", "Month Number", each Date.Month([Dates]), Int64.Type),
    #"Inserted Month ID" = Table.AddColumn(#"Inserted Month Number", "Month ID", each if [Month Number] < #"Inserted Month Number"{1}[Month Number] then 12 - ((#"Inserted Month Number"{1}[Month Number]- 1) - [Month Number]) else [Month Number] - (#"Inserted Month Number"{1}[Month Number] - 1), Int64.Type),
    #"Inserted Actual Year" = Table.AddColumn(#"Inserted Month ID", "Actual Year", each Date.Year([Dates]), Int64.Type),
    #"Added MM/YY" = Table.AddColumn(#"Inserted Actual Year", "MM/YY", each Text.Start([Month Name],3) & "-" & Text.End(Number.ToText([Actual Year]),2), type text),
    #"Grouped Year and Month Name Rows" = Table.Group(#"Added MM/YY", {"Actual Year", "Month Name"}, {{"Month Year ID", each List.Min([Date ID]), type number}}),
    #"Merged Year and Month with Main Query" = Table.NestedJoin(#"Added MM/YY", {"Actual Year", "Month Name"}, #"Grouped Year and Month Name Rows", {"Actual Year", "Month Name"}, "Added Index", JoinKind.LeftOuter),
    #"Added Month Year ID" = Table.ExpandTableColumn(#"Merged Year and Month with Main Query", "Added Index", {"Month Year ID"}, {"Month Year ID"}),
    #"Inserted Actual Quarter" = Table.AddColumn(#"Added Month Year ID", "Actual Quarter", each Date.QuarterOfYear([Dates]), Int64.Type),
    #"Added Actual QQ/YY" = Table.AddColumn(#"Inserted Actual Quarter", "Actual QQ/YY", each "Q" & Number.ToText([Actual Quarter]) & "-" & Text.End(Number.ToText([Actual Year]),2),Text.Type),
    #"Grouped Actual QQ/YY" = Table.Group(#"Added Actual QQ/YY", {"Actual QQ/YY"}, {{"Actual QQ/YY ID", each List.Min([Date ID]), type number}}),
    #"Merged Actual QQ/YY with Main Query" = Table.NestedJoin( #"Added Actual QQ/YY", {"Actual QQ/YY"}, #"Grouped Actual QQ/YY", {"Actual QQ/YY"}, "Grouped Rows", JoinKind.LeftOuter),
    #"Expanded Actual QQ/YY ID" = Table.ExpandTableColumn(#"Merged Actual QQ/YY with Main Query", "Grouped Rows", {"Actual QQ/YY ID"}, {"Actual QQ/YY ID"}),
    #"Grouped Month Name" = Table.Group(#"Expanded Actual QQ/YY ID", {"Month Name"}, {{"Month ID", each List.Min([Month ID]), type number}}),
    #"Removed Alternate Rows" = Table.AlternateRows(#"Grouped Month Name",1,2,1),
    #"Added FQ ID" = Table.AddIndexColumn(#"Removed Alternate Rows", "FQ ID", 1, 1, Int64.Type),
    #"Merged Month Name with Main Query" = Table.NestedJoin(#"Grouped Month Name", {"Month Name"}, #"Added FQ ID", {"Month Name"}, "Added FQ ID", JoinKind.LeftOuter),
    #"Expanded Added QoY ID" = Table.ExpandTableColumn(#"Merged Month Name with Main Query", "Added FQ ID", {"FQ ID"}, {"FQ ID"}),
    #"Sorted Rows by Month ID" = Table.Sort(#"Expanded Added QoY ID",{{"Month ID", Order.Ascending}}),
    #"Filled Down FQ ID" = Table.FillDown(#"Sorted Rows by Month ID",{"FQ ID"}),
    #"Merged Queries1" = Table.NestedJoin(#"Expanded Actual QQ/YY ID", {"Month Name"}, #"Filled Down FQ ID", {"Month Name"}, "Filled Down FQ ID", JoinKind.LeftOuter),
    #"Expanded Filled Down QoY ID" = Table.ExpandTableColumn(#"Merged Queries1", "Filled Down FQ ID", {"FQ ID"}, {"FQ ID"}),
    #"Grouped Month Number, Month ID and Actual Year" = Table.Group(#"Expanded Filled Down QoY ID", {"Month Number", "Month ID", "Actual Year"}, {{"Average", each List.Average([Actual Year]), type number}}),
    #"Added Min Year" = Table.AddColumn(#"Grouped Month Number, Month ID and Actual Year", "Min Year", each if [Month Number] - [Month ID] = #"Grouped Month Number, Month ID and Actual Year"{1}[Month Number] - #"Grouped Month Number, Month ID and Actual Year"{1}[Month ID] then [Actual Year]
else [Actual Year]-1, Int64.Type),
    #"Added Max Year" = Table.AddColumn(#"Added Min Year", "Max Year", each if [Month Number] = [Month ID] then [Actual Year] else if [Month Number] - [Month ID] = #"Added Min Year"{1}[Month Number] - #"Added Min Year"{1}[Month ID] then [Actual Year]+1 else [Actual Year]),
    #"Added Fiscal Year" = Table.AddColumn(#"Added Max Year", "Fiscal Year", each if [Month Number]=[Month ID] then Number.ToText([Actual Year]) else Number.ToText([Min Year]) & "/" & Number.ToText([Max Year]),Text.Type),
    #"Grouped Rows" = Table.Group(#"Added Fiscal Year", {"Fiscal Year"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
    #"Added FY ID" = Table.AddIndexColumn(#"Grouped Rows", "FY ID", 1, 1, Int64.Type),
    #"Merged Queries" = Table.NestedJoin(#"Added Fiscal Year", {"Fiscal Year"}, #"Added FY ID", {"Fiscal Year"}, "Added FY ID", JoinKind.LeftOuter),
    #"Expanded Added FY ID" = Table.ExpandTableColumn(#"Merged Queries", "Added FY ID", {"FY ID"}, {"FY ID"}),
    #"Merged FY and FY ID with Main Query" = Table.NestedJoin(#"Expanded Filled Down QoY ID", {"Month Number", "Month ID", "Actual Year"}, #"Expanded Added FY ID", {"Month Number", "Month ID", "Actual Year"}, "Expanded Grouped Year", JoinKind.LeftOuter),
    #"Expanded Fiscal Year and FY ID" = Table.ExpandTableColumn(#"Merged FY and FY ID with Main Query", "Expanded Grouped Year", {"Fiscal Year", "FY ID"}, {"Fiscal Year", "FY ID"}),
    #"Added FQ/YY" = Table.AddColumn(#"Expanded Fiscal Year and FY ID", "FQ/YY", each "Q" & Number.ToText([FQ ID]) & "-" & [Fiscal Year]),
    #"Grouped FQ/YY" = Table.Group(#"Added FQ/YY", {"FQ/YY"}, {{"FQ/YY ID", each List.Min([Date ID]), type number}}),
    #"Merged FQ/YY with Main Query" = Table.NestedJoin(#"Added FQ/YY", {"FQ/YY"}, #"Grouped FQ/YY", {"FQ/YY"}, "Grouped FQ/YY Rows", JoinKind.LeftOuter),
    #"Expanded FQ/YY ID" = Table.ExpandTableColumn(#"Merged FQ/YY with Main Query", "Grouped FQ/YY Rows", {"FQ/YY ID"}, {"FQ/YY ID"}),
    #"Replaced Wk 52 with Wk1 on New Year" = Table.ReplaceValue( #"Expanded FQ/YY ID" ,each [Week of Year ID] ,each if [Month ID] = 1 and [Week of Year ID] = 52 then 1 else [Week of Year ID],Replacer.ReplaceValue,{"Week of Year ID"}),
    #"Added Day of Month No" = Table.AddColumn(#"Replaced Wk 52 with Wk1 on New Year", "Day of Month", each Date.Day([Dates])),
    #"Added Month In Quarter" = Table.AddColumn(#"Added Day of Month No", "Month In Quarter", each Number.Mod([Month ID] - 1, 3 ) + 1),
    #"Added Year Month No" = Table.AddColumn(#"Added Month In Quarter", "Year Month No", each [FY ID]*12 + [Month ID] - 1),
    #"Added Year Quater No" = Table.AddColumn(#"Added Year Month No", "Year Quarter No", each [FY ID] * 4 + [FQ ID] - 1),
    #"Added Year Week No" = Table.AddColumn(#"Added Year Quater No", "Year Week No", each [FY ID] * 52 + [Week of Year ID] - 1),
    #"Changed Type" = Table.TransformColumnTypes(#"Added Year Week No",{{"Week of Year ID", Int64.Type}, {"Year Month No", Int64.Type}, {"Year Quarter No", Int64.Type}, {"Year Week No", Int64.Type}, {"Day of Month", Int64.Type}, {"Month In Quarter", Int64.Type}})
in
    #"Changed Type"
